# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: carlohcs.com.br 
email: carlohcs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Meu site pessoal! Seja bem-vindo! Geek, apaixonado por web e inovação.
baseurl: "" # the subpath of your site, e.g. /blog http://carlohcs.com.br/blog
url: "https://carlohcs.com.br" # the base hostname & protocol for your site
twitter_username: carlohcs
github_username:  carlohcs

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title -> default
# permalink: /palavra/:title -> outro exemplo
permalink: /:categories/:title
